### PR TITLE
Fix migration notice on new WP install

### LINKED ISSUE #123: Migrate to changesets notice also shows when somebody has directly installed WordPress > 4.7
"Existing Snapshots need to be migrated to Changesets, which was added to core in WordPress 4.7." notice should not show if somebody has directly installed WordPress > 4.7, or there are no changesets to migrate.

May be we can do this here https://github.com/xwp/wp-customize-snapshots/blob/develop/php/class-migrate.php#L51-L57
```
if ( ! $this->is_migrated() ) {
    if ( empty( $this->changeset_migrate( 1, true ) ) ) {
        update_option( self::KEY, 1 );
        return;
    }
    // Add actions...
}
```

### PR DESCRIPTION
**Pull request by PatelUtkarsh**
Fixes #123

### CODE REVIEW

File: tests/php/test-class-migrate.php [hunk 1]
```diff
@@ -108,11 +108,34 @@ function test_is_migrated() {
...
+
+		// If no post to migrate fall back and add option value.
+		$migrate_obj = $this->getMockBuilder( 'CustomizeSnapshots\Migrate' )
+		                ->setMethods( array( 'changeset_migrate' ) )
+		                ->setConstructorArgs( array( $this->plugin ) )
+		                ->getMock();
+		$migrate_obj->expects( $this->once() )
+		        ->method( 'changeset_migrate' )
+		        ->with( 1, true )
+		        ->will( $this->returnValue( false ) );
```
Comment (westonruter) [inline tests/php/test-class-migrate.php:133]: Fancy PHPUnit usage. 👍
